/**
 * Starter catalogue of UK makes, models, generations and trim levels.
 *
 * WHY THIS EXISTS AS HAND-WRITTEN DATA
 * There is no free, complete, machine-readable UK catalogue of models and trims.
 * The obvious candidate - the VCA New Car Fuel Consumption database - used to
 * publish CSV downloads, but as at August 2026 the downloads page redirects to the
 * site root and only the interactive search remains. AutoTrader and similar only
 * expose what happens to be for sale today, which is exactly the limitation you are
 * trying to get around.
 *
 * So this file is a seed: enough to make the browser useful immediately, and a
 * schema for the real thing. Run `npm run data:catalogue` to fold in any CSVs you
 * drop into data/manual/ (a VCA export, a spec sheet, your own research); those
 * rows are merged with this seed.
 *
 * ACCURACY: generation-level, not trim-by-trim. Year ranges are UK on-sale years and
 * are approximate at the boundaries. Engine line-ups changed mid-generation more
 * often than is captured here. Treat it as a shortlist-builder, then verify the
 * specific car. Every row is marked provenance:'seed' so the UI can say so.
 */

const T = {
  m5: { label: '5-speed manual', gearbox: 'manual', gears: 5 },
  m6: { label: '6-speed manual', gearbox: 'manual', gears: 6 },
  a6: { label: '6-speed automatic', gearbox: 'automatic', gears: 6 },
  a7: { label: '7-speed automatic', gearbox: 'automatic', gears: 7 },
  a8: { label: '8-speed automatic', gearbox: 'automatic', gears: 8 },
  a9: { label: '9-speed automatic', gearbox: 'automatic', gears: 9 },
  dct6: { label: '6-speed dual-clutch', gearbox: 'dual-clutch', gears: 6 },
  dct7: { label: '7-speed dual-clutch', gearbox: 'dual-clutch', gears: 7 },
  cvt: { label: 'CVT', gearbox: 'cvt', gears: null },
  single: { label: 'Single-speed', gearbox: 'single-speed', gears: 1 },
}

/**
 * Each entry expands into one row per (body x powertrain x transmission).
 * `trims` are the UK-market trim names for the generation.
 */
export const SEED_MODELS = [
  // ------------------------------------------------------------ superminis --
  {
    make: 'Ford',
    model: 'Fiesta',
    generation: 'Mk7',
    yearFrom: 2008,
    yearTo: 2017,
    bodies: ['hatchback'],
    trims: ['Studio', 'Style', 'Zetec', 'Zetec S', 'Titanium', 'ST-Line', 'ST'],
    powertrains: [
      { fuel: 'petrol', engine: '1.25 Duratec', cc: 1242, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.0 EcoBoost', cc: 999, transmissions: [T.m5, T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.6 EcoBoost (ST)', cc: 1596, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 TDCi', cc: 1499, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 TDCi', cc: 1560, transmissions: [T.m5], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Ford',
    model: 'Fiesta',
    generation: 'Mk8',
    yearFrom: 2017,
    yearTo: 2023,
    bodies: ['hatchback'],
    trims: ['Trend', 'Zetec', 'Titanium', 'ST-Line', 'Vignale', 'Active', 'ST'],
    powertrains: [
      { fuel: 'petrol', engine: '1.1 Ti-VCT', cc: 1084, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.0 EcoBoost', cc: 999, transmissions: [T.m6, T.a6], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.0 EcoBoost mHEV', cc: 999, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.5 EcoBoost (ST)', cc: 1497, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 TDCi', cc: 1499, transmissions: [T.m6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Vauxhall',
    model: 'Corsa',
    generation: 'E',
    yearFrom: 2014,
    yearTo: 2019,
    bodies: ['hatchback'],
    trims: ['Life', 'Design', 'Sting', 'Energy', 'SRi', 'SE', 'Limited Edition', 'VXR'],
    powertrains: [
      { fuel: 'petrol', engine: '1.2', cc: 1229, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.4', cc: 1398, transmissions: [T.m5, T.a6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.0 Turbo', cc: 999, transmissions: [T.m5, T.m6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.3 CDTi', cc: 1248, transmissions: [T.m5, T.m6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Vauxhall',
    model: 'Corsa',
    generation: 'F',
    yearFrom: 2019,
    yearTo: null,
    bodies: ['hatchback'],
    trims: ['SE', 'SRi', 'Elite', 'Design', 'GS Line', 'Ultimate', 'Yes'],
    powertrains: [
      { fuel: 'petrol', engine: '1.2 PureTech', cc: 1199, transmissions: [T.m5, T.m6, T.a8], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 Turbo D', cc: 1499, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'bev', engine: '50 kWh e-Corsa', cc: null, transmissions: [T.single], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Volkswagen',
    model: 'Polo',
    generation: 'Mk6 (AW)',
    yearFrom: 2017,
    yearTo: null,
    bodies: ['hatchback'],
    trims: ['S', 'SE', 'Match', 'Beats', 'R-Line', 'Style', 'Life', 'GTI'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 MPI', cc: 999, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.0 TSI', cc: 999, transmissions: [T.m5, T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TSI (GTI)', cc: 1984, transmissions: [T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 TDI', cc: 1598, transmissions: [T.m5, T.dct7], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Renault',
    model: 'Clio',
    generation: 'Mk4',
    yearFrom: 2012,
    yearTo: 2019,
    bodies: ['hatchback', 'estate'],
    trims: ['Expression', 'Dynamique', 'Dynamique S', 'GT Line', 'Iconic', 'Play', 'RS'],
    powertrains: [
      { fuel: 'petrol', engine: '0.9 TCe', cc: 898, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.2 16V', cc: 1149, transmissions: [T.m5], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 dCi', cc: 1461, transmissions: [T.m5, T.dct6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Peugeot',
    model: '208',
    generation: 'Mk2',
    yearFrom: 2019,
    yearTo: null,
    bodies: ['hatchback'],
    trims: ['Active', 'Allure', 'GT Line', 'GT', 'Style'],
    powertrains: [
      { fuel: 'petrol', engine: '1.2 PureTech', cc: 1199, transmissions: [T.m5, T.m6, T.a8], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 BlueHDi', cc: 1499, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'bev', engine: 'e-208 50 kWh', cc: null, transmissions: [T.single], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Toyota',
    model: 'Yaris',
    generation: 'XP210',
    yearFrom: 2020,
    yearTo: null,
    bodies: ['hatchback'],
    trims: ['Icon', 'Design', 'Excel', 'GR Sport', 'Premiere Edition'],
    powertrains: [
      { fuel: 'petrol', engine: '1.5 VVT-i', cc: 1490, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.5 Hybrid', cc: 1490, transmissions: [T.cvt], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'MINI',
    model: 'Hatch',
    generation: 'F56',
    yearFrom: 2014,
    yearTo: null,
    bodies: ['hatchback'],
    trims: ['One', 'Cooper', 'Cooper S', 'John Cooper Works', 'Classic', 'Sport', 'Exclusive'],
    powertrains: [
      { fuel: 'petrol', engine: '1.5 Cooper', cc: 1499, transmissions: [T.m6, T.a6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 Cooper S', cc: 1998, transmissions: [T.m6, T.a8], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 Cooper D', cc: 1496, transmissions: [T.m6, T.a6], drivetrain: 'fwd' },
    ],
  },

  // ------------------------------------------------------------- family hatch --
  {
    make: 'Ford',
    model: 'Focus',
    generation: 'Mk3',
    yearFrom: 2011,
    yearTo: 2018,
    bodies: ['hatchback', 'estate'],
    trims: ['Studio', 'Style', 'Zetec', 'Zetec S', 'Titanium', 'Titanium X', 'ST-Line', 'ST', 'RS'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 EcoBoost', cc: 999, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.6 Ti-VCT', cc: 1596, transmissions: [T.m5, T.a6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 EcoBoost (ST)', cc: 1999, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.3 EcoBoost (RS)', cc: 2261, transmissions: [T.m6], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '1.5 TDCi', cc: 1499, transmissions: [T.m6, T.a6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 TDCi', cc: 1560, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDCi', cc: 1997, transmissions: [T.m6, T.a6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Ford',
    model: 'Focus',
    generation: 'Mk4',
    yearFrom: 2018,
    yearTo: null,
    bodies: ['hatchback', 'estate'],
    trims: ['Style', 'Zetec', 'Titanium', 'Titanium X', 'ST-Line', 'ST-Line X', 'Vignale', 'Active', 'ST'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 EcoBoost', cc: 999, transmissions: [T.m6, T.a8], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.0 EcoBoost mHEV', cc: 999, transmissions: [T.m6, T.a8], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.3 EcoBoost (ST)', cc: 2261, transmissions: [T.m6, T.a7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 EcoBlue', cc: 1499, transmissions: [T.m6, T.a8], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 EcoBlue', cc: 1995, transmissions: [T.m6, T.a8], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Volkswagen',
    model: 'Golf',
    generation: 'Mk7',
    yearFrom: 2012,
    yearTo: 2020,
    bodies: ['hatchback', 'estate'],
    trims: ['S', 'SE', 'SE Nav', 'Match', 'GT', 'R-Line', 'GTD', 'GTE', 'GTI', 'R'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 TSI', cc: 999, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.4 TSI', cc: 1395, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TSI (GTI)', cc: 1984, transmissions: [T.m6, T.dct6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TSI (R)', cc: 1984, transmissions: [T.m6, T.dct7], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '1.6 TDI', cc: 1598, transmissions: [T.m5, T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'phev', engine: '1.4 TSI GTE', cc: 1395, transmissions: [T.dct6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Volkswagen',
    model: 'Golf',
    generation: 'Mk8',
    yearFrom: 2020,
    yearTo: null,
    bodies: ['hatchback', 'estate'],
    trims: ['Life', 'Style', 'R-Line', 'Match', 'GTD', 'GTE', 'GTI', 'GTI Clubsport', 'R'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 TSI', cc: 999, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.0 eTSI mHEV', cc: 999, transmissions: [T.dct7], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.5 eTSI mHEV', cc: 1498, transmissions: [T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TSI (GTI)', cc: 1984, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'phev', engine: '1.4 TSI GTE', cc: 1395, transmissions: [T.dct6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Skoda',
    model: 'Octavia',
    generation: 'Mk3',
    yearFrom: 2013,
    yearTo: 2020,
    bodies: ['hatchback', 'estate'],
    trims: ['S', 'SE', 'SE L', 'SE Technology', 'Sport Line', 'Laurin & Klement', 'Scout', 'vRS'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 TSI', cc: 999, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.4 TSI', cc: 1395, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TSI (vRS)', cc: 1984, transmissions: [T.m6, T.dct6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 TDI', cc: 1598, transmissions: [T.m5, T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI 4x4', cc: 1968, transmissions: [T.m6], drivetrain: 'awd' },
    ],
  },
  {
    make: 'Skoda',
    model: 'Octavia',
    generation: 'Mk4',
    yearFrom: 2020,
    yearTo: null,
    bodies: ['hatchback', 'estate'],
    trims: ['S', 'SE', 'SE Technology', 'SE L', 'Sport Line', 'Scout', 'vRS'],
    powertrains: [
      { fuel: 'hybrid-petrol', engine: '1.0 TSI mHEV', cc: 999, transmissions: [T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.5 TSI', cc: 1498, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'phev', engine: '1.4 TSI iV', cc: 1395, transmissions: [T.dct6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'SEAT',
    model: 'Leon',
    generation: 'Mk3',
    yearFrom: 2012,
    yearTo: 2020,
    bodies: ['hatchback', 'estate'],
    trims: ['S', 'SE', 'SE Dynamic', 'FR', 'FR Sport', 'Xcellence', 'Cupra'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 TSI', cc: 999, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.4 TSI', cc: 1395, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TSI (Cupra)', cc: 1984, transmissions: [T.m6, T.dct6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 TDI', cc: 1598, transmissions: [T.m5, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Toyota',
    model: 'Corolla',
    generation: 'E210',
    yearFrom: 2019,
    yearTo: null,
    bodies: ['hatchback', 'estate', 'saloon'],
    trims: ['Icon', 'Icon Tech', 'Design', 'Excel', 'GR Sport', 'Trek'],
    powertrains: [
      { fuel: 'petrol', engine: '1.2 Turbo', cc: 1197, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.8 Hybrid', cc: 1798, transmissions: [T.cvt], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '2.0 Hybrid', cc: 1987, transmissions: [T.cvt], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Honda',
    model: 'Civic',
    generation: 'FK8 / FC',
    yearFrom: 2017,
    yearTo: 2021,
    bodies: ['hatchback', 'saloon'],
    trims: ['S', 'SE', 'SR', 'EX', 'Sport', 'Sport Line', 'Prestige', 'Type R'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 VTEC Turbo', cc: 988, transmissions: [T.m6, T.cvt], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.5 VTEC Turbo', cc: 1498, transmissions: [T.m6, T.cvt], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 VTEC Turbo (Type R)', cc: 1996, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 i-DTEC', cc: 1597, transmissions: [T.m6, T.cvt], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Mazda',
    model: '3',
    generation: 'BM',
    yearFrom: 2013,
    yearTo: 2019,
    bodies: ['hatchback', 'saloon'],
    trims: ['SE', 'SE-L', 'SE-L Nav', 'Sport', 'Sport Nav', 'Sport Black'],
    powertrains: [
      { fuel: 'petrol', engine: '2.0 SkyActiv-G', cc: 1998, transmissions: [T.m6, T.a6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.2 SkyActiv-D', cc: 2191, transmissions: [T.m6, T.a6], drivetrain: 'fwd' },
    ],
  },

  // -------------------------------------------------------------- premium --
  {
    make: 'BMW',
    model: '3 Series',
    generation: 'F30',
    yearFrom: 2012,
    yearTo: 2019,
    bodies: ['saloon', 'estate'],
    trims: ['SE', 'Sport', 'Modern', 'Luxury', 'M Sport', 'M Sport Shadow Edition', 'M3'],
    powertrains: [
      { fuel: 'petrol', engine: '1.6 (316i)', cc: 1598, transmissions: [T.m6, T.a8], drivetrain: 'rwd' },
      { fuel: 'petrol', engine: '2.0 (320i / 330i)', cc: 1998, transmissions: [T.m6, T.a8], drivetrain: 'rwd' },
      { fuel: 'petrol', engine: '3.0 (340i)', cc: 2998, transmissions: [T.m6, T.a8], drivetrain: 'rwd' },
      { fuel: 'diesel', engine: '2.0 (318d / 320d)', cc: 1995, transmissions: [T.m6, T.a8], drivetrain: 'rwd' },
      { fuel: 'diesel', engine: '2.0 xDrive (320d)', cc: 1995, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '3.0 (330d / 335d)', cc: 2993, transmissions: [T.a8], drivetrain: 'rwd' },
      { fuel: 'phev', engine: '2.0 (330e)', cc: 1998, transmissions: [T.a8], drivetrain: 'rwd' },
    ],
  },
  {
    make: 'BMW',
    model: '3 Series',
    generation: 'G20',
    yearFrom: 2019,
    yearTo: null,
    bodies: ['saloon', 'estate'],
    trims: ['SE', 'Sport', 'M Sport', 'M Sport Pro', 'M340i', 'M3'],
    powertrains: [
      { fuel: 'hybrid-petrol', engine: '2.0 mHEV (320i / 330i)', cc: 1998, transmissions: [T.a8], drivetrain: 'rwd' },
      { fuel: 'hybrid-petrol', engine: '3.0 mHEV (M340i)', cc: 2998, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'hybrid-diesel', engine: '2.0 mHEV (320d)', cc: 1995, transmissions: [T.a8], drivetrain: 'rwd' },
      { fuel: 'hybrid-diesel', engine: '3.0 mHEV (330d)', cc: 2993, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'phev', engine: '2.0 (330e)', cc: 1998, transmissions: [T.a8], drivetrain: 'rwd' },
    ],
  },
  {
    make: 'Audi',
    model: 'A3',
    generation: '8V',
    yearFrom: 2012,
    yearTo: 2020,
    bodies: ['hatchback', 'saloon', 'convertible'],
    trims: ['SE', 'SE Technik', 'Sport', 'S line', 'Black Edition', 'S3', 'RS3'],
    powertrains: [
      { fuel: 'petrol', engine: '1.0 TFSI', cc: 999, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.4 TFSI', cc: 1395, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '2.0 TFSI (S3)', cc: 1984, transmissions: [T.m6, T.dct7], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '1.6 TDI', cc: 1598, transmissions: [T.m5, T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI quattro', cc: 1968, transmissions: [T.m6, T.dct6], drivetrain: 'awd' },
      { fuel: 'phev', engine: '1.4 TFSI e-tron', cc: 1395, transmissions: [T.dct6], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Audi',
    model: 'A4',
    generation: 'B9',
    yearFrom: 2015,
    yearTo: null,
    bodies: ['saloon', 'estate'],
    trims: ['SE', 'Sport', 'S line', 'Black Edition', 'Vorsprung', 'S4', 'RS4'],
    powertrains: [
      { fuel: 'petrol', engine: '2.0 TFSI', cc: 1984, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '3.0 TFSI (S4)', cc: 2995, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '2.0 TDI', cc: 1968, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 TDI quattro', cc: 1968, transmissions: [T.dct7], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '3.0 TDI quattro', cc: 2967, transmissions: [T.a8], drivetrain: 'awd' },
    ],
  },
  {
    make: 'Mercedes-Benz',
    model: 'C-Class',
    generation: 'W205',
    yearFrom: 2014,
    yearTo: 2021,
    bodies: ['saloon', 'estate', 'coupe', 'convertible'],
    trims: ['SE', 'Sport', 'AMG Line', 'AMG Line Premium', 'AMG Line Night Edition', 'AMG C 43', 'AMG C 63'],
    powertrains: [
      { fuel: 'petrol', engine: '1.6 (C 180)', cc: 1595, transmissions: [T.m6, T.a9], drivetrain: 'rwd' },
      { fuel: 'petrol', engine: '2.0 (C 200 / C 300)', cc: 1991, transmissions: [T.a9], drivetrain: 'rwd' },
      { fuel: 'petrol', engine: '4.0 V8 (AMG C 63)', cc: 3982, transmissions: [T.a9], drivetrain: 'rwd' },
      { fuel: 'diesel', engine: '1.6 (C 200 d)', cc: 1598, transmissions: [T.m6, T.a9], drivetrain: 'rwd' },
      { fuel: 'diesel', engine: '2.0 (C 220 d / C 300 d)', cc: 1950, transmissions: [T.a9], drivetrain: 'rwd' },
      { fuel: 'phev', engine: '2.0 (C 300 de / C 300 e)', cc: 1950, transmissions: [T.a9], drivetrain: 'rwd' },
    ],
  },
  {
    make: 'Volvo',
    model: 'XC60',
    generation: 'Mk2',
    yearFrom: 2017,
    yearTo: null,
    bodies: ['suv'],
    trims: ['Momentum', 'R-Design', 'Inscription', 'Plus', 'Ultimate', 'Polestar Engineered'],
    powertrains: [
      { fuel: 'petrol', engine: '2.0 T5', cc: 1969, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'hybrid-petrol', engine: '2.0 B5 mHEV', cc: 1969, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '2.0 D4', cc: 1969, transmissions: [T.a8], drivetrain: 'fwd' },
      { fuel: 'hybrid-diesel', engine: '2.0 B4 mHEV', cc: 1969, transmissions: [T.a8], drivetrain: 'awd' },
      { fuel: 'phev', engine: '2.0 T8 Recharge', cc: 1969, transmissions: [T.a8], drivetrain: 'awd' },
    ],
  },

  // ------------------------------------------------------------------ SUVs --
  {
    make: 'Nissan',
    model: 'Qashqai',
    generation: 'J11',
    yearFrom: 2013,
    yearTo: 2021,
    bodies: ['suv'],
    trims: ['Visia', 'Acenta', 'Acenta Premium', 'N-Connecta', 'Tekna', 'Tekna+', 'N-Motion'],
    powertrains: [
      { fuel: 'petrol', engine: '1.2 DIG-T', cc: 1197, transmissions: [T.m6, T.cvt], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.3 DIG-T', cc: 1332, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.5 dCi', cc: 1461, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 dCi', cc: 1598, transmissions: [T.m6, T.cvt], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '1.6 dCi 4WD', cc: 1598, transmissions: [T.m6], drivetrain: 'awd' },
    ],
  },
  {
    make: 'Nissan',
    model: 'Qashqai',
    generation: 'J12',
    yearFrom: 2021,
    yearTo: null,
    bodies: ['suv'],
    trims: ['Visia', 'Acenta Premium', 'N-Connecta', 'Tekna', 'Tekna+', 'N-Design'],
    powertrains: [
      { fuel: 'hybrid-petrol', engine: '1.3 DIG-T mHEV', cc: 1332, transmissions: [T.m6, T.cvt], drivetrain: 'fwd' },
      { fuel: 'hybrid-petrol', engine: '1.3 DIG-T mHEV 4WD', cc: 1332, transmissions: [T.cvt], drivetrain: 'awd' },
      { fuel: 'hybrid-petrol', engine: '1.5 e-POWER', cc: 1497, transmissions: [T.single], drivetrain: 'fwd' },
    ],
  },
  {
    make: 'Kia',
    model: 'Sportage',
    generation: 'QL',
    yearFrom: 2016,
    yearTo: 2021,
    bodies: ['suv'],
    trims: ['1', '2', '3', '4', 'GT-Line', 'GT-Line S', 'Edition 25'],
    powertrains: [
      { fuel: 'petrol', engine: '1.6 GDi', cc: 1591, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.6 T-GDi', cc: 1591, transmissions: [T.m6, T.dct7], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '1.6 CRDi', cc: 1598, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 CRDi', cc: 1995, transmissions: [T.m6, T.a6], drivetrain: 'awd' },
    ],
  },
  {
    make: 'Hyundai',
    model: 'Tucson',
    generation: 'TL',
    yearFrom: 2015,
    yearTo: 2020,
    bodies: ['suv'],
    trims: ['S', 'S Connect', 'SE', 'SE Nav', 'Premium', 'Premium SE', 'N Line'],
    powertrains: [
      { fuel: 'petrol', engine: '1.6 GDi', cc: 1591, transmissions: [T.m6], drivetrain: 'fwd' },
      { fuel: 'petrol', engine: '1.6 T-GDi', cc: 1591, transmissions: [T.m6, T.dct7], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '1.6 CRDi', cc: 1598, transmissions: [T.m6, T.dct7], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 CRDi', cc: 1995, transmissions: [T.m6, T.a6], drivetrain: 'awd' },
    ],
  },
  {
    make: 'Land Rover',
    model: 'Discovery Sport',
    generation: 'L550',
    yearFrom: 2014,
    yearTo: null,
    bodies: ['suv'],
    trims: ['S', 'SE', 'HSE', 'HSE Luxury', 'R-Dynamic S', 'R-Dynamic SE', 'R-Dynamic HSE'],
    powertrains: [
      { fuel: 'petrol', engine: '2.0 Si4 / P200', cc: 1998, transmissions: [T.a9], drivetrain: 'awd' },
      { fuel: 'diesel', engine: '2.0 TD4 / eD4', cc: 1999, transmissions: [T.m6, T.a9], drivetrain: 'fwd' },
      { fuel: 'diesel', engine: '2.0 SD4 / D180', cc: 1999, transmissions: [T.a9], drivetrain: 'awd' },
      { fuel: 'phev', engine: '1.5 P300e', cc: 1498, transmissions: [T.a8], drivetrain: 'awd' },
    ],
  },

  // ------------------------------------------------------------- electric --
  {
    make: 'Tesla',
    model: 'Model 3',
    generation: 'Highland / pre-Highland',
    yearFrom: 2019,
    yearTo: null,
    bodies: ['saloon'],
    trims: ['Standard Range Plus', 'Rear-Wheel Drive', 'Long Range', 'Performance'],
    powertrains: [
      { fuel: 'bev', engine: 'RWD', cc: null, transmissions: [T.single], drivetrain: 'rwd' },
      { fuel: 'bev', engine: 'Dual Motor Long Range', cc: null, transmissions: [T.single], drivetrain: 'awd' },
      { fuel: 'bev', engine: 'Dual Motor Performance', cc: null, transmissions: [T.single], drivetrain: 'awd' },
    ],
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    generation: 'ZE1',
    yearFrom: 2018,
    yearTo: 2024,
    bodies: ['hatchback'],
    trims: ['Visia', 'Acenta', 'N-Connecta', 'Tekna', 'e+ Tekna'],
    powertrains: [
      { fuel: 'bev', engine: '40 kWh', cc: null, transmissions: [T.single], drivetrain: 'fwd' },
      { fuel: 'bev', engine: '62 kWh e+', cc: null, transmissions: [T.single], drivetrain: 'fwd' },
    ],
  },
]
